export const STUDENTS_SEED = [
"ABBEY Yves Roland","ABEKA Kouassi Papa","ABOUBACAR Balkissa","ACHI Mariette Charlene",
"ADANLETE Kangni St D'assus","ADINGRA Koffi Evrard Lopez","ADJANI Nadia Kashifat",
"ADON Gnangui Arnold Onezimex","ADOU Yaoua Beman Yann-Ursule","AFFOUN Kouadio Cynan",
"AGNAN Erica Oceane Akabla","AGNIMOU Gnandja Grace Sorania","AGOUALE Amoin Eunice Sybelle",
"AGUIE Aye Yannick Wilfried","AHIDJE Akoua Dan Abigail","AHISSAN Brou Yah Roxie Samira Desiree",
"AHONGBONONBABATOUNDE Harold Othniel","AHOUA Amichia Gnoan Ulrich","AKE Chia Rosemonde",
"AKOTAN Bodoua Guy Evrard","AKOU Api Axelle Berenice","AKPINDRIN Othniel Hans Emmanuel",
"AKRE Danho Alexandra Hermance Rebecca","ALHASSANE Mariam","ALLANGBA Charlone Fleur Emmanuella",
"ALLOUKO Fiankan Jean-Marc Theoxane","AMISSALE Brou Emmanuel","AMON Animan Josephine Carmel",
"ASSEMIAN Kouame Josue","ASSEMIEN Ama Alida Maxime","ASSI Chia Marie-Audrey",
"ASSIENE Yoboue Amoin Grace Andree","ASSIHE N'guessan Jean Ives Israel","ASSOMA Assoma Ange Junior",
"ATCHADE N'guessan Rodolphe","ATCHIN Peggy Koim","ATSEYE Akoua Laurette Eloise",
"ATTA N'dri Amon Grace Fabienne","AYARA Anselme Romuald Baby","AYEDA Kochikpa Modest",
"BA LOU Bouzie Anne Berenice","BADO Zeinab Nancy Wambui","BADOU Kouame Pierre Elam Adriel",
"BAGATE Tianda Zainab","BAGAYOKO Bakary","BAH Hadjiratou","BAH Tode Zeinatte",
"BAMBA Abou","BAMBA Chiaka","BAMBA Ismael Aziz","BAMBA Issiaka",
"BATI BI Tuhan Wilfried Arond","BENE N'cho Steve Firmin","BERTE N'gniere Bintou",
"BILSON Essi Ange Aurelius","BLE Dogore Malika Priscille","BLEOUE Eva Marie Eloise",
"BOA BI Sika Jean Martial","BOGUE Doah Cesar Elischamad","BOLLY Grace Emmanuella",
"BOMBET Elohica Michele-Herve","BOUEDJE Ngbocho Harris Bernard Ake","BOUSSIN Kouame Frederic",
"BROU Gemima Grace Aya","BROU N'guessan Reine Berenice","BROU OI Brou Jules Landry",
"CAMARA Mombatchoh","CHERIF Sara Haidara","CISSE Mohamed Aziz","COMBASSERE Anderson Keiri",
"COULIBALY Brahima","COULIBALY Cheick Tayourou","COULIBALY Kolo Marie Noelle",
"COULIBALY Largaton Zie Alex","COULIBALY Salia","COULIBALY Tiatiala Myriam",
"COULIBALY Tuonrona","COULIBALY Zokongnon Anne Laetitia","DAHIE Gilles Florien Gouzile",
"DAHOUE Allassane","DAMOLETORA Bissari Bogora Abel","DANHO Rolande Phanuelle",
"DEDO Grace Emmanuelle","DEHOUAN Fidele Bolina","DEMBELE Issiaka","DEMBELE N'guessan Marie Michelle",
"DIABATE Tcheple Marie-Laurence","DIAKITE Allassane Roger","DIALLO Ablan Grace Emmanuella",
"DIARASSOUBA Abdoul","DIARRA Aly","DIBY DIBY Rene","DIOMANDE Gondo Samuel Epaphras",
"DJAMA N'cho Kouassi Joel","DJAMA Nobi Marcel Elias","DJOLLO Bohui Privat",
"DJONDE Gueassohou Ruth Marie-Audrey","DOLE BAYO Marc Orin","DOSSO Aicha Cynthia",
"DOUA MAKADO Victoire Elisabeth","DOUDOU Eunice Triphene","DOUMBIA Aboubakar William Kader",
"DOUMBIA Lamine","DRABO Ouroukayatou","DRAMANE Kone","DROH YONGA Astrid Amira Flore",
"EKISSI Wossoh Aude Maeva","ESSOH Esmel Joel-Prince Saint Cyr","ETIEN Dollo Chrys Emmanuel",
"FANNY Aboubacar","FLAN Zranglo Esla","FOLOCHO Mohamed Ramadane",
"GAH SEDA Younao Leonce","GBANE Souga Mahama","GBAZI Francisca Lisa Marie-Camille",
"GBOCHU Blah Doriane Esther Vanessa","GNAGOH Kaka Hugues Armand","GODDE Ossyane Simon Fegues",
"GOHI LOU Koue Sonia","GOMUN Badieu Sunga Hilarie","GOUAMENE Kieta Helena",
"GOUANKE Franck Ebenezer","GUEU Jacques","HILY Hamidou","HOUIDIKPO Djedje Romeo",
"IKE Prince Ikenna","ILBOUDO Oumarou","ILHYAS Abdul Quoyum","INCHO Annette Ornella Rita",
"IRITIE BI Peter Aime Stephane","ISSELMOU Yahya Ahmdi","KABA Oskane N'faly Junior",
"KABRAN Kouao-Bile Augustin Belisaire","KAMAGATE Adjara","KAMGAINGMATIO Grace Daniella",
"KANGA Aya Sandrine Herminia","KAREEM Faisatu Iyabo Ayoni","KASSAMBA Awa","KEGLO Amavi Sidonie",
"KESSE Koffi Junior Joseph Elisee Djetouan","KLA MOUSSO Claudine","KODJO Beko Yves Henock",
"KOFFI Aboh Anicet Marius","KOFFI Affoue Tatiana Yvette","KOFFI Akoua Marie",
"KOFFI Attouman Patrick","KOFFI Bate N'siake Ange Hostelle","KOFFI Goyo Isaac David",
"KOFFI Kouadio Joel","KOFFI N'like Philippe Adams","KOFFI Ruth Axelle Deborah",
"KOFFI Yah Amoin Ida Jennifer","KOFFI Yao Emmanuel Manet","KOFFI Yeni Marie Kevine",
"KONAN Christ Armel Kevin","KONAN Djethy Regis-Ivans","KONAN Konan Isaac","KONAN Konan Junior",
"KONAN Salifou","KONE Awa Rania","KONE Brahima","KONE Grace-Deborah","KONE Kanidan Oceane",
"KONE Katchin Sanga","KONE Kiyali M'bantchin Esther","KONE Koupitienhan Mariam",
"KONE Meman Ben Kader","KONE Moussa","KONE Movaly","KONE Nassarata",
"KONE Noufo Check Oumar Joackim","KONE Ouahogninlin Bienvenue Mahny Estella",
"KONE Wawota Petio Marylin Alexia","KONE Zana Ibrouhaim","KOSSAN Gonto Aslaire",
"KOSSONOU Koffi Ange Samuel","KOUA Affi Yannick Salvador Junior","KOUADIO Ahou Carmel Geraldine",
"KOUADIO Ange Aristide Kouassi","KOUADIO Aya Hermance","KOUADIO Joyce Othniel-Jonathan",
"KOUADIO Konan Jean-Baptiste","KOUADIO Kouassi Andre Junior","KOUADIO Toto Joseph",
"KOUAKOU Assena Sainzet Danielle","KOUAKOU Assoh Evelyne Prunelle",
"KOUAKOU Chris Ettien Yannick Dorgeles","KOUAKOU Ezekiel Herbert","KOUAKOU Koffi Casimir",
"KOUAKOU Koffi Francis","KOUAKOU N'da Brou Simone","KOUAKOU Yao Ferdinand",
"KOUAME Ahou Grace Marie-Therese","KOUAME Assassy Geraude Cefora","KOUAME Attomoly Grace Emmanuella",
"KOUAME Djenan Aya Sara","KOUAME Grace-Esther","KOUAME Koffi Parfait",
"KOUAME Marie Esther Sthella","KOUAME Prince Kouadio Mermoz","KOUAME Yao Ezekiel",
"KOUAME Yao Jean-Herve","KOUASSI Affoue Louise","KOUASSI Amani Charles","KOUASSI Amenan Orlane",
"KOUASSI Assale Alexandre","KOUASSI Bah Marc Arthur Kouassi","KOUASSI Bi Djessan Euphreme",
"KOUASSI Guy Laure Tchimi","KOUASSI Kouabenan Jean Thierry","KOUASSI Kouadio Moise",
"KOUASSI Kouakou Ange Felicien","KOUASSI N'guessan Dieudonne","KOUASSI-BLE Ericka Charlyne",
"KOUDOU Guissi Prince Joane","KOUTOUAN Lidwine Candice","KRA Adoni Jean Brice",
"KRA Affoua Fofie Ines Ange","KRAMO Doh Emmanuel Axel Junior","KROCO Kacou Acouba Grace Nancy",
"LEKEU TCHOUMI Steve Rayan","LIGUE Gbadji Ange-Emmanuelle","LOUADE Banty Evodie",
"MADADJA Kouadio Ange Armel","MAFO Dasse Solane","MAHI Boris Anderson","M'BAI Bogbe Justin",
"MEITE Ali Massoma Ben Aboubakar","MELI KENFACK Pamela","METANGMO TANKEU Sandra",
"MIAN YAKRE Adjo Marlene Esther","MOUDO Leopold Majoie","MOUNET Jeannette Marie Emmanuelle",
"NAHI Gogoua Eliezer","NAJWA Fouad Sidani","NASSA Djega Claude Emmanuella",
"N'DOLI Nsieny Ruth D'avila Epiphanie","N'DRAMAN Yao Eugene","N'DRE Aya Darille",
"N'DRI Adjoua Grace Andrea","N'DRI Kouadio Bah Didier","N'GORAN Ahou Mathilde Janviere",
"N'GUESSAN Esther Aniela","N'GUESSAN Konan Ange Poligor","N'GUESSAN Konan Dany Serge",
"N'GUESSAN Yapo Ephraim","N'GUETTA Jessica Kevine Rhesa","NGUEULEU DJEUGA Laetitia Henitsoa",
"NIAMIEN Brou Carlos","NOUBIWEANDEM Priscillia Grace","ODO Affoue Henriette Christelle Ashley",
"OKA Renee Emmanuelle","OKOMA Adepo Elohim Schadrac","OUATTARA Adjaratou",
"OUATTARA Fougnigue Zie Youssouf","OUATTARA Gouenin Marc Tresor","OUATTARA Idrissa",
"OUATTARA Yeo Donignon Dorcas","OUATTARA Zanga Hamed","OULOTO Kamondje Joel Landry",
"OUSSOU Amoin Marie-Christelle","PALE Toho","POBA Alice Merveille","PONY MAPCHE Yvanie Lucresse",
"SANDJIMAN MAKUBA Laurette","SANHOURI Amani Luc Maxence Regis","SANOGO Karamoko",
"SAVANE SY Hadja Maferima","SERI Faussignaux Franck Noex","SETIN Zroassy Linda Marylise",
"SIDIBE Oumar","SINAN Limata Mado Victoria Laure","SIP Abou","SOGODOGO Mamadou",
"SORO Dofouingnon Marguerite","SORO Fougnigue Djeneba Jeanne","SORO Katie",
"SORO Lagnon Nina Antoinette","SORO N'dahanfowa Nafissiata","SOUANGA Ahou Anne Esther",
"SOUMAHORO Noura Mandognan","SOUMAHORO Sibi Fougnigue","SRAKA Koffi Anthony",
"SYLLA Lacine Junior","SYLLA Tenin Nanan Kady","TAH Thizie Johao Yasmin Josue",
"TALL Ousmane","TANOH Akissi Yvonne","TANOH Bosson Marie Estelle",
"TANOH KAKOU Jean Daniel Epiphane","TANON MIHBE Mamadou","TAPSOBA Awa Yasmine",
"TCHETCHE Lynda-Colombe","TIJANI Rokibat Omowumi Abake","TIMITE Abdel Chakour Magic",
"TOUALY Samira Erim Noemie","TRA BI GOHIZIE Achille Christophers","TRA LOU TANAN Armandine",
"TRAYE BI IRIE Terry Arnold","WOKAMSIMO Elisabeth Patricia","YAO Amoin Rebeca",
"YAO Gnissan Yah Seraphin Junior","YAO Hauleblai Abaud Jaures Berenis","YAO Jean Yves Jonas",
"YAO Kan Claude Ephrem","YAO Koffi Sem Emmanuel","YAO Kouadio Evariste",
"YAO KOUAKOU Ange Fregist","YAO N'GUESSAN Ruth Marie Colombe","YARA Balkissou",
"YARABE Marie-Elvire Sephora","YEO Dokatiene Alassane","YEO Kolotcholoman Jean Marie",
"YEO N'danfolo Desire","YEPIE WOSSE Ines Davila","YOUAN BI Lezie Stephane","ZIKE Ange Michel Mondesir"
].map((nom, i) => {
  const tres = i % 2 === 0
    ? { name: 'Yarabe', phone: '2250544993454' }
    : { name: 'Assassy', phone: '2250788222743' }
  return { id: String(i), nom, ticket: 'Solo', total: 30000, tresoriere: tres.name, tresPhone: tres.phone, pin: null, paye: 0 }
})
